# Generated by Django 5.0.3 on 2024-03-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='likesnum',
            new_name='likes_num',
        ),
    ]
